name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: install ctags
      run: sudo apt-get install -y universal-ctags
    - name: install readline
      run: sudo apt-get install -y readline-common libreadline-dev
    - name: install makedepend
      run: sudo apt-get install -y xutils-dev
    - name: clone picky
      run: git clone https://github.com/lcn2/picky
    - name: install picky
      run: cd picky && sudo make install
    - name: make clobber all
      run: make clobber all
    - name: pwd
      run: pwd
    - name: ls -a
      run: ls -a
    - name: make prep
      run: make prep
    - name: make clobber
      run: make clobber
